#!/bin/sh

# usage: ugoira-merge [-d] file.zip file.json
# dependencies: sed, zip

if [ "$1" = "-d" ]; then
    delete_after_processing=1
    shift
fi

zipf="$1"
jsonf="$2"
basef="$(echo "$zipf" | sed 's/\.zip$//')"
ugoiraf="$basef"".ugoira"
tempdir=$(mktemp -d)

cleanup() { rm -r "$tempdir"; }
trap cleanup INT TERM QUIT

cp "$zipf" "$ugoiraf"
cp "$jsonf" "$tempdir/animation.json"
zip -uj0 "$ugoiraf" "$tempdir/animation.json"
cleanup
[ -n "$delete_after_processing" ] && rm "$zipf" "$jsonf"
