#!/bin/sh

# usage: ugoira-merge-batch [-d] file...

export IFS="
"

if [ "$1" = "-d" ]; then
    um_flags="-d"
    shift
fi

# prevent empty first line
files="$1"
shift

for i in "$@"; do
    files="$files
$i"
done

files="$(echo "$files" | sed -e 's/\.json//g' -e 's/\.zip//g' | sort | uniq)"

for i in $files; do
    ugoira-merge $um_flags "$i".zip "$i".json
done
